#!/usr/bin/env python3
"""
python/aerograph-sdk/tools/generate_contracts.py

Generate Pydantic v2 models from the JSON Schema artifact.

This script:
1. Reads packages/schema-exporter/artifacts/1.0.0/trace-event.schema.json
2. Invokes datamodel-code-generator to produce Pydantic v2 models
3. Writes the output to src/aerograph_sdk/contracts/generated.py

Usage:
    cd python/aerograph-sdk
    python tools/generate_contracts.py

Requirements:
    pip install datamodel-code-generator>=0.25.0

Note: The generated output is committed to the repository. This script
is only run by maintainers when the schema changes.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

# Paths (all relative to repo root)
REPO_ROOT = Path(__file__).parents[3]
ARTIFACT_PATH = (
    REPO_ROOT
    / "packages"
    / "schema-exporter"
    / "artifacts"
    / "1.0.0"
    / "trace-event.schema.json"
)
OUTPUT_PATH = (
    Path(__file__).parents[1] / "src" / "aerograph_sdk" / "contracts" / "generated.py"
)
CONFIG_PATH = Path(__file__).parent / "datamodel-codegen.toml"


def main() -> None:
    if not ARTIFACT_PATH.exists():
        print(
            f"ERROR: JSON Schema artifact not found at {ARTIFACT_PATH}\n"
            "Run `npm run schema:export` first to generate it.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Extract the pythonCodegenSchema to a temp file
    import json
    import tempfile

    with open(ARTIFACT_PATH, "r", encoding="utf-8") as f:
        artifact = json.load(f)

    python_schema = artifact.get("pythonCodegenSchema")
    if not python_schema:
        print("ERROR: pythonCodegenSchema not found in artifact", file=sys.stderr)
        sys.exit(1)

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".json", delete=False, encoding="utf-8"
    ) as temp_f:
        json.dump(python_schema, temp_f)
        temp_schema_path = temp_f.name

    print(f"[generate_contracts] Input (temp): {temp_schema_path}")
    print(f"[generate_contracts] Output: {OUTPUT_PATH}")

    # Ensure output dir exists
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Run datamodel-codegen
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(temp_schema_path),
            "--input-file-type",
            "jsonschema",
            "--output",
            str(OUTPUT_PATH),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--target-python-version",
            "3.10",
            "--use-annotated",
            "--use-standard-collections",
            "--use-union-operator",
            "--disable-timestamp",
            "--strict-nullable",
            "--collapse-root-models",
            "--custom-file-header",
            "# generated by datamodel-codegen:\n#   filename:  trace-event.schema.json",
        ],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
    )

    # Cleanup temp file
    import os

    try:
        os.remove(temp_schema_path)
    except OSError:
        pass

    if result.returncode != 0:
        print(
            f"ERROR: datamodel-code-generator failed:\n{result.stderr}", file=sys.stderr
        )
        sys.exit(1)

    print(f"[generate_contracts] [OK] Generated {OUTPUT_PATH}")

    # Append SCHEMA_VERSION
    import json

    with open(ARTIFACT_PATH) as f:
        artifact = json.load(f)
    version = artifact.get("schemaVersion", "1.0.0")

    with open(OUTPUT_PATH, "a") as f:
        f.write("\n# Injected by generate_contracts.py\n")
        f.write(f"SCHEMA_VERSION = '{version}'\n")
        f.write(
            "TraceEvent = PromptEvent | ResponseEvent | ToolCallEvent | ToolResultEvent | HandoffEvent | ErrorEvent | NoteEvent | StateSnapshotEvent | RetrieverEvent | CheckpointEvent\n"
        )

    print(
        "[generate_contracts] NOTE: Review the generated file for correctness "
        "before committing."
    )


if __name__ == "__main__":
    main()
